---
- hosts: all
  gather_facts: true
  become: yes

  vars:
    home: /home/bm
    ruby_version: 2.3.1
    app_dir: /opt/beautiful-mimic

  tasks:
    - include: ../tasks/users.yml

    - include: ../tasks/sidekiq.yml

    - include: ../tasks/compute.yml

    - name: 'Install packages'
      yum: name=ImageMagick
