---
- hosts: all
  gather_facts: true

  vars:
    - compute_dir: /opt/compute
    - torch_dir: '{{compute_dir}}/lib/torch'
    - neural_dir: '{{compute_dir}}/lib/neural-style'
  
  tasks:
  - name: 'Add key to aptitude to install mongodb'
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927
    sudo: yes
    
  - name: 'Add mongodb to sources list'
    shell: 'echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list'
    args:
      creates: /etc/apt/sources.list.d/mongodb-org-3.2.list
    sudo: yes

  - name: 'Update cache'
    apt: update_cache=true
    sudo: yes

  - name: 'Install mongodb-org'
    apt: name='mongodb-org=3.2.*'
    sudo: yes

  - name: 'Copy script to disable transparent hugepages'
    copy: src=../files/disable-transparent-hugepages.sh dest=/etc/init.d/disable-transparent-hugepages owner=root group=root mode=0755
    sudo: yes

  - name: 'Run script to disable transparent hugepages'
    shell: /etc/init.d/disable-transparent-hugepages 
    sudo: yes

  - name: 'Use init.d to disable transparent hugepages on restart'
    shell: 'update-rc.d disable-transparent-hugepages defaults'
    sudo: yes
