---
- hosts: all
  gather_facts: true
  become: yes

  vars:
    home: /home/bm
    ruby_version: 2.3.1
    app_dir: /opt/beautiful-mimic

  tasks:
    - include: ../tasks/users.yml

    - include: ../tasks/sidekiq.yml

    - include: ../tasks/generator.yml

    - name: 'Download training data'
      unarchive: 'src=http://msvocds.blob.core.windows.net/coco2014/train2014.zip dest={{app_dir}}/neural-style/ remote_src=yes copy=no owner=bm group=bm'
