source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.6'
gem 'unicorn', '~> 5.0.1'
gem 'mongoid', '~> 5.1.0'
gem 'aws-sdk', '~> 2.2.8'
gem 'mini_magick', '~> 4.3.6'
gem 'sidekiq', '~> 4.0.1'
gem 'sass', '~> 3.4.19'

group :test do
  gem 'rspec', '~> 3.4.0'
  gem 'rack-test', '~> 0.6.3'
end
