- name: 'Install packages'
  yum: 'name={{item}} update_cache=yes'
  become_user: root
  with_items:
    - python27
    - atlas-devel
    - git
    - htop

- name: 'Create compute directory structure'
  file: path={{app_dir}} state=directory owner=bm group=bm
  become_user: root

- name: 'Updgrade pip'
  pip: 'name=pip state=latest virtualenv={{app_dir}}/venv_2_7'
  become_user: bm

- name: 'Install pip modules'
  pip: 'name={{item.name}} version={{item.version}} virtualenv={{app_dir}}/venv_2_7'
  with_items:
    - { name: NumPy, version: 1.11 }
    - { name: six, version: 1.9 }
    - { name: pillow, version: 3.3.1 }
  become_user: bm

# - name: 'Copy cudnn files into place'
#   unarchive: src=../files/cudnn-7.5-linux-x64-v5.1.tgz dest=/opt/nvidia/ owner=root group=root creates=/opt/nvidia/cuda/include/cudnn.h
#   become_user: root
#
# - name: 'Take ownership of cuda'
#   file: path=/opt/nvidia/cuda owner=bm group=bm recurse=yes
#   become_user: root
#
- name: 'Install chainer'
  pip: 'name=chainer virtualenv={{app_dir}}/venv_2_7'
  environment:
    CPATH: /opt/nvidia/cuda/include:$CPATH
    LIBRARY_PATH: /opt/nvidia/cuda/lib:$LIBRARY_PATH
    LD_LIBRARY_PATH: /opt/nvidia/cuda/lib:$LD_LIBRARY_PATH
  become_user: bm

- name: 'Clone utility repo'
  git: 'repo=https://github.com/6o6o/chainer-fast-neuralstyle.git dest={{app_dir}}/neural-style version=c273247'
  become_user: bm
